diff_cont:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.19
    wheel_radius: 0.07
    cmd_vel_timeout: 0.25
    publish_rate: 50.0
    base_frame_id: base_link
    use_stamped_vel: false
