slam_toolbox:
  ros__parameters:
    use_sim_time: true
    odom_frame: odom
    map_frame: map
    base_frame: base_link
    map_file_name: ""
    resolution: 0.1
    mode: "mapping"
    scan_topic: "/scan"