controller_server:
  ros__parameters:
    controller_frequency: 10.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.5
    min_theta_threshold: 0.001
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "nav2_regulated_pure_pursuit_controller::RegulatedPurePursuitController"
      desired_linear_vel: 0.5
      base_frame: "base_link"
      transform_tolerance: 0.1
      use_velocity_scaled_lookahead_dist: true

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.5
      use_astar: false

behavior_server:
  ros__parameters:
    behavior_tree_path: "navigate_w_replanning_and_recovery.xml"
    global_frame: "map"
    robot_base_frame: "base_link"

bt_navigator:
  ros__parameters:
    global_frame: "map"
    robot_base_frame: "base_link"
    odom_topic: "/odom"

smoother_server:
  ros__parameters:
    smoother_plugins: ["SmoothPath"]

waypoint_follower:
  ros__parameters:
    loop_rate: 20.0

amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"

slam_toolbox:
  ros__parameters:
    map_frame: "map"
    base_frame: "base_link"
    odom_frame: "odom"
    scan_topic: "/scan"
    use_sim_time: True
    resolution: 0.05